FOOD_CATALOG_SEED = [
    {
        "food_name": "白飯",
        "aliases": ["白飯", "白米飯", "米飯"],
        "category": "staple",
        "locale": "zh-TW",
        "serving_reference": "1 bowl",
        "calories_per_serving": 280,
        "protein_g": 5,
        "carbs_g": 62,
        "fat_g": 0.6,
        "sugar_g": 0,
        "sodium_mg": 4,
        "fiber_g": 0.8,
        "source_name": "TW common foods",
        "verified": True,
    },
    {
        "food_name": "炸雞腿",
        "aliases": ["炸雞腿", "雞腿", "雞腿便當主菜"],
        "category": "protein",
        "locale": "zh-TW",
        "serving_reference": "1 piece",
        "calories_per_serving": 285,
        "protein_g": 23,
        "carbs_g": 10,
        "fat_g": 17,
        "sugar_g": 0,
        "sodium_mg": 420,
        "fiber_g": 0,
        "source_name": "TW common foods",
        "verified": True,
    },
    {
        "food_name": "烤雞胸",
        "aliases": ["雞胸", "雞胸肉", "烤雞胸", "舒肥雞胸"],
        "category": "protein",
        "locale": "zh-TW",
        "serving_reference": "1 fillet",
        "calories_per_serving": 165,
        "protein_g": 31,
        "carbs_g": 0,
        "fat_g": 3.6,
        "sugar_g": 0,
        "sodium_mg": 90,
        "fiber_g": 0,
        "source_name": "TW common foods",
        "verified": True,
    },
    {
        "food_name": "茶葉蛋",
        "aliases": ["茶葉蛋", "雞蛋"],
        "category": "protein",
        "locale": "zh-TW",
        "serving_reference": "1 egg",
        "calories_per_serving": 70,
        "protein_g": 6.3,
        "carbs_g": 0.6,
        "fat_g": 4.8,
        "sugar_g": 0.3,
        "sodium_mg": 75,
        "fiber_g": 0,
        "source_name": "TW common foods",
        "verified": True,
    },
    {
        "food_name": "豆腐",
        "aliases": ["豆腐", "嫩豆腐", "板豆腐"],
        "category": "protein",
        "locale": "zh-TW",
        "serving_reference": "1 serving",
        "calories_per_serving": 90,
        "protein_g": 9,
        "carbs_g": 3,
        "fat_g": 5,
        "sugar_g": 1,
        "sodium_mg": 16,
        "fiber_g": 1,
        "source_name": "TW common foods",
        "verified": True,
    },
    {
        "food_name": "豆干",
        "aliases": ["豆干", "豆乾"],
        "category": "protein",
        "locale": "zh-TW",
        "serving_reference": "1 serving",
        "calories_per_serving": 85,
        "protein_g": 8.5,
        "carbs_g": 3.5,
        "fat_g": 4.4,
        "sugar_g": 1.2,
        "sodium_mg": 210,
        "fiber_g": 1.2,
        "source_name": "TW common foods",
        "verified": True,
    },
    {
        "food_name": "高麗菜",
        "aliases": ["高麗菜", "炒高麗菜"],
        "category": "vegetable",
        "locale": "zh-TW",
        "serving_reference": "1 serving",
        "calories_per_serving": 38,
        "protein_g": 1.8,
        "carbs_g": 6.8,
        "fat_g": 0.5,
        "sugar_g": 3.3,
        "sodium_mg": 80,
        "fiber_g": 2.4,
        "source_name": "TW common foods",
        "verified": True,
    },
    {
        "food_name": "青菜",
        "aliases": ["青菜", "燙青菜", "蔬菜"],
        "category": "vegetable",
        "locale": "zh-TW",
        "serving_reference": "1 serving",
        "calories_per_serving": 35,
        "protein_g": 2.1,
        "carbs_g": 5,
        "fat_g": 0.5,
        "sugar_g": 1.8,
        "sodium_mg": 70,
        "fiber_g": 2.8,
        "source_name": "TW common foods",
        "verified": True,
    },
    {
        "food_name": "花椰菜",
        "aliases": ["花椰菜", "青花菜", "綠花椰"],
        "category": "vegetable",
        "locale": "zh-TW",
        "serving_reference": "1 serving",
        "calories_per_serving": 45,
        "protein_g": 3.7,
        "carbs_g": 7.2,
        "fat_g": 0.6,
        "sugar_g": 1.7,
        "sodium_mg": 45,
        "fiber_g": 3.1,
        "source_name": "TW common foods",
        "verified": True,
    },
    {
        "food_name": "地瓜",
        "aliases": ["地瓜", "番薯", "烤地瓜"],
        "category": "staple",
        "locale": "zh-TW",
        "serving_reference": "1 medium piece",
        "calories_per_serving": 120,
        "protein_g": 2,
        "carbs_g": 28,
        "fat_g": 0.2,
        "sugar_g": 7,
        "sodium_mg": 55,
        "fiber_g": 4,
        "source_name": "TW common foods",
        "verified": True,
    },
    {
        "food_name": "紅茶",
        "aliases": ["紅茶", "冰紅茶", "奶茶以外的紅茶"],
        "category": "beverage",
        "locale": "zh-TW",
        "serving_reference": "1 cup",
        "calories_per_serving": 120,
        "protein_g": 0,
        "carbs_g": 30,
        "fat_g": 0,
        "sugar_g": 30,
        "sodium_mg": 20,
        "fiber_g": 0,
        "source_name": "TW common foods",
        "verified": True,
    },
    {
        "food_name": "無糖茶",
        "aliases": ["無糖茶", "無糖紅茶", "無糖綠茶"],
        "category": "beverage",
        "locale": "zh-TW",
        "serving_reference": "1 cup",
        "calories_per_serving": 0,
        "protein_g": 0,
        "carbs_g": 0,
        "fat_g": 0,
        "sugar_g": 0,
        "sodium_mg": 5,
        "fiber_g": 0,
        "source_name": "TW common foods",
        "verified": True,
    },
    {
        "food_name": "珍珠奶茶",
        "aliases": ["珍奶", "珍珠奶茶", "奶茶"],
        "category": "beverage",
        "locale": "zh-TW",
        "serving_reference": "1 cup",
        "calories_per_serving": 430,
        "protein_g": 3,
        "carbs_g": 70,
        "fat_g": 10,
        "sugar_g": 55,
        "sodium_mg": 180,
        "fiber_g": 1,
        "source_name": "TW common foods",
        "verified": True,
    },
    {
        "food_name": "無糖豆漿",
        "aliases": ["無糖豆漿", "豆漿"],
        "category": "beverage",
        "locale": "zh-TW",
        "serving_reference": "1 cup",
        "calories_per_serving": 120,
        "protein_g": 9,
        "carbs_g": 8,
        "fat_g": 6,
        "sugar_g": 4,
        "sodium_mg": 95,
        "fiber_g": 2,
        "source_name": "TW common foods",
        "verified": True,
    },
    {
        "food_name": "滷肉飯",
        "aliases": ["滷肉飯", "魯肉飯"],
        "category": "mixed",
        "locale": "zh-TW",
        "serving_reference": "1 bowl",
        "calories_per_serving": 520,
        "protein_g": 14,
        "carbs_g": 63,
        "fat_g": 22,
        "sugar_g": 6,
        "sodium_mg": 720,
        "fiber_g": 1.5,
        "source_name": "TW common foods",
        "verified": True,
    },
    {
        "food_name": "牛肉麵",
        "aliases": ["牛肉麵"],
        "category": "mixed",
        "locale": "zh-TW",
        "serving_reference": "1 bowl",
        "calories_per_serving": 610,
        "protein_g": 28,
        "carbs_g": 68,
        "fat_g": 24,
        "sugar_g": 7,
        "sodium_mg": 1850,
        "fiber_g": 3.5,
        "source_name": "TW common foods",
        "verified": True,
    },
    {
        "food_name": "炒飯",
        "aliases": ["炒飯"],
        "category": "mixed",
        "locale": "zh-TW",
        "serving_reference": "1 plate",
        "calories_per_serving": 700,
        "protein_g": 18,
        "carbs_g": 92,
        "fat_g": 26,
        "sugar_g": 6,
        "sodium_mg": 980,
        "fiber_g": 2.5,
        "source_name": "TW common foods",
        "verified": True,
    },
    {
        "food_name": "水餃",
        "aliases": ["水餃", "餃子"],
        "category": "mixed",
        "locale": "zh-TW",
        "serving_reference": "10 pieces",
        "calories_per_serving": 500,
        "protein_g": 20,
        "carbs_g": 58,
        "fat_g": 18,
        "sugar_g": 3,
        "sodium_mg": 760,
        "fiber_g": 3,
        "source_name": "TW common foods",
        "verified": True,
    },
]
